### ISSUE TITLE
Query string split broken (and missing test)

### ISSUE THREAD

**Issue by mindplay-dk** [baryshev/TreeRoute#6]
I don't think [this](https://github.com/baryshev/TreeRoute/blob/master/src/Router.php#L14) or [this](https://github.com/baryshev/TreeRoute/blob/master/src/Router.php#L59) does what you think it does:

```
$parts = explode('?', $url, 1);
```

With a limit of 1, it will always return a 1-dimensional array, e.g.:

```
var_dump(explode('?', 'hello?world', 1)); // => array(0 => 'hello?world')
```

The limit should be 2, not 1, I think?

You probably should add a test-case for the query string split.

I would PR, but my codebase doesn't look anything like yours anymore...

**Comment by mindplay-dk** [comment]
Come to think of it, that line should probably just be deleted from `addRoute()`, you're not going to use query params when defining routes :-)

**Comment by mindplay-dk** [comment]
Also, I wonder, what was the intended behavior here: is it supposed to discard the query string, or should it actually parse the query string and present the vars?

What's the use-case where you will pass a query string and expect it to be ignored?

Ignoring things is always risky. Though I'm not sure if the correct behavior is to (A) throw an exception, because you shouldn't be passing a URL with a query string, because no behavior is defined for that case, or (B) parse the query string contents. (although that raises more questions: do you mix query string vars in with captured params, or place them in a separate collection? perhaps the simplest solution is to throw, since, most likely, the query string has already been parsed by PHP anyhow, and the result is already available in `$_GET`?)

**Comment by baryshev** [comment]
Thank you! Sorry for the long response. It fixed now.
